name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: abaplint
      uses: abaplint/actions-abaplint@hvam/test0111
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
